apiVersion: v1
kind: Pod
metadata:
  name: hydra-migrate
  namespace: tradistonks
  labels:
    app: hydra-migrate
spec:
  containers:
    - args:
        - migrate
        - sql
        - --yes
        - -e
      env:
        - name: LOG_LEVEL
          value: debug
        - name: HYDRA_SECRETS_SYSTEM
          valueFrom:
            configMapKeyRef:
              key: HYDRA_SECRETS_SYSTEM
              name: env
        - name: DSN
          valueFrom:
            configMapKeyRef:
              key: HYDRA_DSN
              name: env
      image: oryd/hydra:v1.10.2
      name: hydra-migrate
      resources: {}
  restartPolicy: OnFailure
status: {}
