apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hydra
  namespace: tradistonks
  labels:
    app: hydra
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: oauth2.tradistonks.qtmsheep.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hydra
                port:
                  number: 4444
