apiVersion: v1
kind: Service
metadata:
  name: hydra-postgres
  namespace: tradistonks
  labels:
    app: hydra-postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: hydra-postgres
status:
  loadBalancer: {}
