apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hydra-postgres-data
  namespace: tradistonks
  labels:
    app: hydra-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
