apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-logs
  namespace: tradistonks
  labels:
    app: mongodb-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
